# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(629, 556)
        Dialog.setMinimumSize(QtCore.QSize(500, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top = QtWidgets.QFrame(Dialog)
        self.Top.setMaximumSize(QtCore.QSize(16777212, 50))
        self.Top.setStyleSheet("background-color: rgb(0, 204, 122);")
        self.Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setObjectName("Top")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Top)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Title = QtWidgets.QLabel(self.Top)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        self.label_Title.setFont(font)
        self.label_Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Title.setStyleSheet("")
        self.label_Title.setTextFormat(QtCore.Qt.AutoText)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout_2.addWidget(self.label_Title)
        self.verticalLayout.addWidget(self.Top)
        self.frame_Content = QtWidgets.QFrame(Dialog)
        self.frame_Content.setStyleSheet("background-color: black;")
        self.frame_Content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Content.setObjectName("frame_Content")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Content)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_Window = QtWidgets.QFrame(self.frame_Content)
        self.frame_Window.setMaximumSize(QtCore.QSize(500, 500))
        self.frame_Window.setStyleSheet("background-color: rgb(38, 37, 37);\n"
"border-radius: 2px;")
        self.frame_Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Window.setObjectName("frame_Window")
        self.label_Text = QtWidgets.QLabel(self.frame_Window)
        self.label_Text.setGeometry(QtCore.QRect(10, 100, 91, 40))
        self.label_Text.setMinimumSize(QtCore.QSize(20, 20))
        self.label_Text.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"border-radius: 5px;")
        self.label_Text.setIndent(5)
        self.label_Text.setObjectName("label_Text")
        self.label_Key = QtWidgets.QLabel(self.frame_Window)
        self.label_Key.setGeometry(QtCore.QRect(10, 160, 91, 20))
        self.label_Key.setMinimumSize(QtCore.QSize(20, 20))
        self.label_Key.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"border-radius: 5px;")
        self.label_Key.setIndent(5)
        self.label_Key.setObjectName("label_Key")
        self.lineEdit_Text = QtWidgets.QLineEdit(self.frame_Window)
        self.lineEdit_Text.setGeometry(QtCore.QRect(110, 100, 371, 40))
        self.lineEdit_Text.setStyleSheet("QLineEdit{\n"
"background-color: rgb(100, 100, 100);\n"
"border-radius: 3px;\n"
"border: 0px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(213, 211, 211);\n"
"border-radius: 3px;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_Text.setObjectName("lineEdit_Text")
        self.lineEdit_Key = QtWidgets.QLineEdit(self.frame_Window)
        self.lineEdit_Key.setGeometry(QtCore.QRect(110, 160, 161, 20))
        self.lineEdit_Key.setStyleSheet("QLineEdit{\n"
"background-color: rgb(100, 100, 100);\n"
"border-radius: 3px;\n"
"border: 0px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(213, 211, 211);\n"
"border-radius: 3px;\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.lineEdit_Key.setText("")
        self.lineEdit_Key.setObjectName("lineEdit_Key")
        self.label_Instruction = QtWidgets.QLabel(self.frame_Window)
        self.label_Instruction.setGeometry(QtCore.QRect(10, 9, 481, 81))
        self.label_Instruction.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        self.label_Instruction.setFont(font)
        self.label_Instruction.setStyleSheet("QLabel{\n"
"background-color: rgb(141, 141, 141);\n"
"border-radius: 10px;\n"
"\n"
"}")
        self.label_Instruction.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Instruction.setObjectName("label_Instruction")
        self.pushButton_Cript = QtWidgets.QPushButton(self.frame_Window)
        self.pushButton_Cript.setGeometry(QtCore.QRect(280, 190, 100, 30))
        self.pushButton_Cript.setStyleSheet("QPushButton{\n"
"background-color: rgb(100, 100, 100);\n"
"border-radius: 3px;\n"
"border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 211, 211);\n"
"border-radius: 3px;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: red;\n"
"color:white;\n"
"border-radius: 3px;\n"
"border: 2px solid black;\n"
"}")
        self.pushButton_Cript.setObjectName("pushButton_Cript")
        self.pushButton_Decript = QtWidgets.QPushButton(self.frame_Window)
        self.pushButton_Decript.setGeometry(QtCore.QRect(390, 190, 100, 30))
        self.pushButton_Decript.setStyleSheet("QPushButton{\n"
"background-color: rgb(100, 100, 100);\n"
"border-radius: 3px;\n"
"border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 211, 211);\n"
"border-radius: 3px;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: red;\n"
"color:white;\n"
"border-radius: 3px;\n"
"border: 2px solid black;\n"
"}")
        self.pushButton_Decript.setObjectName("pushButton_Decript")
        self.label_Answer = QtWidgets.QLabel(self.frame_Window)
        self.label_Answer.setGeometry(QtCore.QRect(10, 230, 481, 201))
        self.label_Answer.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label_Answer.setFont(font)
        self.label_Answer.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"border-radius: 10px;")
        self.label_Answer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Answer.setObjectName("label_Answer")
        self.gridLayout.addWidget(self.frame_Window, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_Content)
        self.Botton = QtWidgets.QFrame(Dialog)
        self.Botton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Botton.setStyleSheet("background-color: rgb(0, 204, 122);")
        self.Botton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Botton.setObjectName("Botton")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Botton)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Button = QtWidgets.QLabel(self.Botton)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        self.label_Button.setFont(font)
        self.label_Button.setStyleSheet("")
        self.label_Button.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Button.setObjectName("label_Button")
        self.verticalLayout_3.addWidget(self.label_Button)
        self.verticalLayout.addWidget(self.Botton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_Title.setText(_translate("Dialog", "Crypt Text - Your Coder/Decoder text"))
        self.label_Text.setText(_translate("Dialog", "Frase"))
        self.label_Key.setText(_translate("Dialog", "TextLabel"))
        self.lineEdit_Text.setPlaceholderText(_translate("Dialog", "Insira a frase"))
        self.lineEdit_Key.setPlaceholderText(_translate("Dialog", "Insira a chave"))
        self.label_Instruction.setText(_translate("Dialog", "Adicione o texto na primeira linha e a chave de Criptografia/Decriptografia.\n"
"Após isso, selecione o botão desejado.\n"
"!Atenção! Ao escolher a chave, use apenas letras, não use simbolos ou espaços"))
        self.pushButton_Cript.setText(_translate("Dialog", "Criptografar"))
        self.pushButton_Decript.setText(_translate("Dialog", "Decriptografar"))
        self.label_Answer.setText(_translate("Dialog", "Test Text"))
        self.label_Button.setText(_translate("Dialog", "Luis Filipe - Program in development - 2023, Brazil  "))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
    '''
